config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get 'pages/scanner'
  post "pages/addScan", to: 'pages#addScan',:as => :addScan

  resources :barcodes
  post "barcodes/createBarcodes", to: 'barcodes#createBarcodes',:as => :createBarcodes
  resources :teams
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/barcode.rb
class Barcode < ApplicationRecord
  belongs_to :team
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :barcodes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/barcodes_controller.rb
class BarcodesController < ApplicationController
  before_action :set_barcode, only: [:show, :edit, :update, :destroy]

  # GET /barcodes
  # GET /barcodes.json
  def index
    @barcodes = Barcode.all
  end

  # GET /barcodes/1
  # GET /barcodes/1.json
  def show
  end

  # GET /barcodes/new
  def new
    @barcode = Barcode.new
    @teams = Team.all
  end

  # GET /barcodes/1/edit
  def edit
    @teams = Team.all
  end

  # POST /barcodes
  # POST /barcodes.json
  def create
    @barcode = Barcode.new(barcode_params)

    respond_to do |format|
      if @barcode.save
        format.html { redirect_to @barcode, notice: 'Barcode was successfully created.' }
        format.json { render :show, status: :created, location: @barcode }
      else
        format.html { render :new }
        format.json { render json: @barcode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /barcodes/1
  # PATCH/PUT /barcodes/1.json
  def update
    respond_to do |format|
      if @barcode.update(barcode_params)
        format.html { redirect_to @barcode, notice: 'Barcode was successfully updated.' }
        format.json { render :show, status: :ok, location: @barcode }
      else
        format.html { render :edit }
        format.json { render json: @barcode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /barcodes/1
  # DELETE /barcodes/1.json
  def destroy
    @barcode.destroy
    respond_to do |format|
      format.html { redirect_to barcodes_url, notice: 'Barcode was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def createBarcodes
    amount = params[:count]
    team = params[:team]

    for i in 1..amount.to_i do
      barcode = Barcode.new
      barcode.team_id = team

      barcode.save
    end

    redirect_to team_path(team)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_barcode
      @barcode = Barcode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def barcode_params
      params.require(:barcode).permit(:team_id, :scan)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    maleteams = Team.where(gender: true)
    femaleteams = Team.where(gender: false)
    maleAmount = []
    maleLabels = []
    femaleAmount = []
    femaleLabels = []
    maleteams.each do |a|
      maleAmount.push a.amount
      maleLabels.push a.name
    end
    femaleteams.each do |a|
      femaleAmount.push a.amount
      femaleLabels.push a.name
    end
    gon.watch.maleteamsAmount = maleAmount
    gon.maleteamsLabels = maleLabels
    gon.watch.femaleteamsAmount = femaleAmount
    gon.femaleteamsLabels = femaleLabels
  end

  def scanner

  end

  def addScan
      barcode = Barcode.find(params[:id])
      team = barcode.team
      if barcode.scan == false then
        barcode.scan = true
        team.amount = team.amount + 10
        team.save
        barcode.save
      end
      redirect_to pages_scanner_path
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all

    respond_to do |format|
      format.html
      format.pdf do
        pdf = MarkenPdf.new(@teams)

        send_data pdf.render,
            filename: "wertmarken",
            type: 'application/pdf',
            disposition: 'inline'
      end
    end
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: 'Team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:name, :gender, :amount, :color)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/barcodes_helper.rb
module BarcodesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/barcodes/_form.haml
= simple_form_for(@barcode) do |f|
  = f.error_notification
  .form-inputs
    = f.association :team
    = f.input :scan
  .form-actions
    = f.button :submit

app/views/barcodes/edit.html.erb
<h1>Editing Barcode</h1>

<%= render 'form', barcode: @barcode %>

<%= link_to 'Show', @barcode %> |
<%= link_to 'Back', barcodes_path %>

app/views/barcodes/index.haml
%p#notice= notice
%h1 Barcodes
%table
  %thead
    %tr
      %th ID
      %th Team
      %th Scan
      %th{:colspan => "3"}
  %tbody
    - @barcodes.each do |barcode|
      %tr
        %td= barcode.id
        %td= barcode.team.name
        %td= barcode.scan
        %td= link_to 'Show', barcode
        %td= link_to 'Edit', edit_barcode_path(barcode)
        %td= link_to 'Destroy', barcode, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Barcode', new_barcode_path

app/views/barcodes/new.html.erb
<h1>New Barcode</h1>

<%= render 'form', barcode: @barcode %>

<%= link_to 'Back', barcodes_path %>

app/views/barcodes/show.haml
%p#notice= notice
%p
  %strong Team:
  = @barcode.team.name
= link_to 'Edit', edit_barcode_path(@barcode)
|
\#{link_to 'Back', barcodes_path}

app/views/layouts/application.haml
!!!
%html
  %head
    %title Thekengold
    = csrf_meta_tags
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    - if params[:action] == "index"
      -if params[:controller] == "pages"
        %meta{:content => "5", "http-equiv" => "refresh"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = Gon::Base.render_data
  %body
    .container-fluid
      = yield

app/views/pages/index.haml
%canvas#femaleChart
%canvas#maleChart

app/views/pages/scanner.haml
= form_tag({controller: "pages", action: "addScan"}, method: "post") do
  = text_field_tag "id",'', autofocus: true
  = submit_tag "Erstellen"